# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
remote_theme: 'mmistakes/minimal-mistakes'
minimal_mistakes_skin: 'air' # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: 'en-US'
title: 'Jeffrey Florek'
name: 'Jeffrey Florek'
description: 'My personal site.'
masthead_title: 'JF' # overrides the website title displayed in the masthead, use " " for no title

# Social Sharing
twitter:
  username: 'jeffreyflorek'

# Site Author
author:
  name: 'Jeffrey Florek'
  avatar: '/assets/images/bio-photo.jpg' # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: 'Engineer, nerd, etc.'
  location: 'New York, NY'
  links:
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/jeffreyflorek'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/jeffreyflorek'
    - label: 'Instagram'
      icon: 'fab fa-fw fa-instagram'
      url: 'https://instagram.com/jeff.florek'

# Site Footer
footer:
  links:
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/jeffreyflorek'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/jeffreyflorek'
    - label: 'Instagram'
      icon: 'fab fa-fw fa-instagram'
      url: 'https://instagram.com/jeff.florek'

# Reading Files
include:
  - _pages

# Conversion
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: 'America/New_York' # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: single
      author_profile: true
